site_name: Octoposh
theme: readthedocs
repo_url: https://github.com/Dalmirog/Octoposh

pages:
- Home: index.md

- Getting Started:
  - Installing the Module: gettingstarted/installing-the-module.md
  - Setting credentials: gettingstarted/setting-credentials.md

- Cmdlets:
  - Get-OctopusChannel: cmdlets/get-octopuschannel.md
  - Get-OctopusChannel: cmdlets/get-octopuschannel.md
  - Get-OctopusConnectionInfo: cmdlets/get-octopusconnectioninfo.md
  - Get-OctopusDashboard: cmdlets/get-octopusdashboard.md
  - Get-OctopusDeployment: cmdlets/get-octopusdeployment.md
  - Get-OctopusEnvironment: cmdlets/get-octopusenvironment.md
  - Get-OctopusFeed: cmdlets/get-octopusfeed.md
  - Get-OctopusLifecycle: cmdlets/get-octopuslifecycle.md
  - Get-OctopusMachine: cmdlets/get-octopusmachine.md
  - Get-OctopusProject: cmdlets/get-octopusproject.md
  - Get-OctopusProjectGroup: cmdlets/get-octopusprojectgroup.md
  - Get-OctopusRelease: cmdlets/get-octopusrelease.md
  - Get-OctopusResourceModel: cmdlets/get-octopusresourcemodel.md
  - Get-OctopusServerThumbprint: cmdlets/get-octopusserverthumbprint.md
  - Get-OctopusTagSet: cmdlets/get-octopustagset.md
  - Get-OctopusTeam: cmdlets/get-octopusteam.md
  - Get-OctopusTenant: cmdlets/get-octopustenant.md
  - Get-OctopusToolPath: cmdlets/get-octopustoolpath.md
  - Get-OctopusToolsFolder: cmdlets/get-octopustoolsfolder.md
  - Get-OctopusToolVersion: cmdlets/get-octopustoolversion.md
  - Get-OctopusUser: cmdlets/get-octopususer.md
  - Get-OctopusVariableSet: cmdlets/get-octopusvariableset.md
  - Install-OctopusTool: cmdlets/install-octopustool.md
  - New-OctopusConnection: cmdlets/new-octopusconnection.md
  - New-OctopusResource: cmdlets/new-octopusresource.md
  - Remove-OctopusResource: cmdlets/remove-octopusresource.md
  - Set-OctopusConnectionInfo: cmdlets/set-octopusconnectioninfo.md
  - Set-OctopusReleaseStatus: cmdlets/set-octopusreleasestatus.md
  - Set-OctopusToolPath: cmdlets/set-octopustoolpath.md
  - Set-OctopusToolsFolder: cmdlets/set-octopustoolsfolder.md
  - Update-OctopusResource: cmdlets/update-octopusresource.md

- Advanced Examples:
  - Running deployments with Octoposh: advancedexamples/running-deployments-with-octoposh.md
  - Creating Resources: advancedexamples/creating-resources.md
  - Deleting Resources: advancedexamples/deleting-resources.md
  - Modifying Resources: advancedexamples/modifying-resources.md

- Release Notes: releasenotes/release-notes.md
