site_name: Octoposh
theme: readthedocs
repo_url: https://github.com/Dalmirog/Octoposh

pages:
- Home: index.md   

- Cmdlets:
  - Get-OctopusChannel: cmdlets/get-octopuschannel.md
  - Get-Whatever: cmdlets/get-octopuschannel.md  
